raspberrypi/userland

host_applications/linux/apps/raspicam/RaspiStill.c
host_applications/linux/apps/raspicam/RaspiStillYUV.c

The old if condition has set the frameNextMethod to FRAME_NEXT_FOREVER if "-t 0" was specified unless the frameNextMethode was FRAME_NEXT_KEYPRESS.

Fix if condition to not overwrite already set frameNextMethod.

---

host_applications/linux/apps/raspicam/RaspiStill.c
host_applications/linux/apps/raspicam/RaspiStillYUV.c
host_applications/linux/apps/raspicam/RaspiVid.c
host_applications/linux/apps/raspicam/RaspiVidYUV.c

It is signalled by the camera when no data is received on the CSI-2
bus. Handle it specifically to try and avoid a bundle of duplicate
forum posts.

Add an error message for MMAL_EVENT_ERROR

---

host_applications/linux/apps/raspicam/RaspiCamControl.c
host_applications/linux/apps/raspicam/RaspiCamControl.h
host_applications/linux/apps/raspicam/RaspiStill.c
host_applications/linux/apps/raspicam/RaspiVid.c

Support for stereoscopic - options 
`-3d [sbs|tb]`    selects side by side, or top/bottom  
`-3dswap`    to swap the two channels.
`-dec`   to reduce the width/height of each image by a factor of 2.
Support for more annotation options:
`-ae <text size> <text colour> <background colour>`. 
text_size is 6 to 160.
colours are YUV as hex 0xVVUUYY. Text colour only uses Y at the moment.
(Thought I'd done this pull request a while back, but obviously not).

Raspistill/vid: More annotate options, and stereoscopic support.

---

host_applications/linux/apps/raspicam/RaspiVid.c

check mmal_port_parameter_get() succeeds when getting
the default intra refresh values. It fails on older firmware.
Fixes #238

Fix intra-refresh port parameter setting.

---

buildme
interface/mmal/vc/CMakeLists.txt

As per commit text.
- buildme dropped into the cross compile path when building on Pi2, so didn't install.
- enable zero copy within MMAL.

Zero copy, and buildme change for Pi2

---

host_applications/linux/apps/hello_pi/hello_fft/makefile

Same patch as https://github.com/raspberrypi/firmware/pull/422 for the firmware repository: The reason, why I added a new target "all" is that without it, the script /opt/vc/src/hello_pi/rebuild.sh only builds hello_fft.bin, but not hello_fft_2d.bin.

Added "all" target to hello_fft/makefile

---

host_applications/linux/apps/raspicam/RaspiCamControl.c

This should be a fixed shutter speed mode, but the behavior depends on how MMAL interprets this setting.  In any case it works, I am not sure what exactly it ends up doing but it is analogous to having awb=off option.

Add exposure=off option

---

host_applications/linux/apps/raspicam/RaspiVid.c

These changes allow users to stream video directly over network with lower latency (bypassing pipes and buffers). If file name has format tcp://host:port then TCP connection to host:port is opened. Similarly if udp:// is used, UDP packets with data are sent to host:port.

Added support for network and fflush to decrease latency.

---

interface/vmcs_host/vc_vchi_dispmanx.c

It would be nice if there was a standardized way to instruct applications to use a certain display, without having to patch the application's source code.
Proposing a VC_DISPLAY environment variable for this purpose.
To force display on HDMI one could then execute:
```
VC_DISPLAY=5 any-egl-application
```
Similar to the standardized DISPLAY variable used by X11 applications.

Proposing VC_DISPLAY env variable

---

host_applications/linux/apps/raspicam/RaspiCamControl.c

Before this change the parameter "--annotate 12ab" annotates with a date.
Replaces pull request #266 incorporating suggested changes.

determine better whether annotation is a bitmask or string

---

host_applications/linux/apps/raspicam/RaspiVidYUV.c

When building with a musl based toolchain, the build fails with the
following message:
host_applications/linux/apps/raspicam/CMakeFiles/raspividyuv.dir/RaspiVidYUV.c.o
In file included from
error: conflicting type qualifiers for ‘stderr’
extern FILE *stderr, *stdout;
^
That's because musl defines stderr and stdout as a const pointer:
extern FILE *const stdin;
extern FILE *const stdout;
extern FILE *const stderr;
And the application (RaspiVidYUV.c) don't:
extern FILE *stderr, *stdout;
Since this declaration already comes in on the header (stdio.h),
there is no need to add an extern declaration, so removes it to
fix the build problem with the musl libc.
Signed-off-by: Sergio Prado <sergio.prado@e-labworks.com>

Fix error when building against musl libc.

---

host_applications/linux/apps/raspicam/RaspiStill.c
host_applications/linux/apps/raspicam/RaspiStillYUV.c
host_applications/linux/apps/raspicam/RaspiVid.c
host_applications/linux/apps/raspicam/RaspiVidYUV.c
host_applications/linux/apps/raspicam/gl_scenes/models.c
host_applications/linux/apps/smem/smem.c

This is just a small patch That I have been using to build my userland deb files with gcc5, most of it is pretty safe and harmless, mostly printf (and friends) to fputs and such.
The inline declarations is the only one I'm not sure would be backwards compat and none of my build systems have gcc4.9 or are none GNUC to test on.
Be nice to get this accepted so I no longer have to patch my builds anymore.

GCC5 fixes

---

host_applications/linux/apps/raspicam/RaspiStill.c

Fix RaspiStill compiler warnings:
- discards const qualifier
- implicit declaration of function isdigit

RaspiStill: Fix compiler warnings

---

host_applications/linux/apps/raspicam/RaspiStillYUV.c

This PR adds a manual flush after writing the image data to stdout.
Without the flush, using signals to stream image data over stdout would result in the missing data, if the image didn't completely fill the buffer.
For validation, a 640x480 YUV image will consist of the following number of bytes:
* Y: 640 x 480 = 307200 bytes
* U: 640 x 480 ÷ 4 = 76800 bytes
* V: 640 x 480 ÷ 4 = 76800 bytes
* Sum: **460800 bytes**.
Prior to the patch, this is what happens when you pipe the image data over standard out and wait for SIGUSR1 to take a shot.
```sh
raspiyuv -o - -w 640 -h 480  --nopreview --signal | wc
18134    2498  458752
```
Notice how `458752` is exactly `7 x 65536`. *It's missing the remaining `2048` bytes*, which doesn't automatically trigger a flush.
And after the patch:
```sh
$ …
```

raspiyuv: Flush stdout to ensure image is fully sent

---

interface/mmal/mmal.h

- Changed declaration of buffer header variable in documentation
code example to use name "buffer" instead of "header" since
this is the name used throughout the remaining code.

Fixed variable name error in code example doc

---

interface/vmcs_host/vc_tvservice.h

Replace `</DNF>` with `</DFN>`

Fix comment markup typos

---

makefiles/cmake/vmcs.cmake

Allow to override VMCS_INSTALL_PREFIX to be able to install to a user defined place

Allow to override VMCS_INSTALL_PREFIX

---

host_applications/linux/apps/raspicam/RaspiStill.c

if (-this_delay_ms < -state->timelapse/2), -this_delay_ms is always positive,
and -state->timelapse/2 is negative, so this if is never true.  The if
condition should be if (-this_delay_ms < state->timelapse/2).

Wrong sign in if condition

---

host_applications/linux/apps/raspicam/RaspiCamControl.c

Valid --drc options are mentioned in the Notes (just like the valid options for --exposure, --awb, --imxfx and --metering)

Update raspicam helptext

---

interface/khronos/common/khrn_client.c
interface/khronos/common/khrn_client_rpc.h
interface/khronos/common/linux/khrn_client_platform_linux.c
interface/khronos/common/linux/khrn_client_rpc_linux.c
interface/khronos/egl/egl_client_surface.c
interface/khronos/ext/egl_khr_sync_client.c

PID namespacing breaks VCHIQ as it uses PIDs as unique identifiers for VCHIQ services, meaning messages sent from userland will contain a different ID than the one expected by the GPU.
This patch addresses the problem uses the existing GET_CLIENT_ID ioctl (via `vchiq_get_client_id()`) to retrieve the global PID as seen by the kernel rather than using the process's reported PID.
The main situation that causes this problem to occur is when trying to run code that interfaces with the GPU inside of a container (e.g. via EGL.)
I'm not certain this is the best means of achieving this aim, however I definitely think the fix belongs in the userland tools, as the kernel alternative is to either use the namespaced PID, which opens the door to conflicts (see …

khronos: Use vchiq_get_client_id to determine global PID.

---

host_applications/linux/apps/raspicam/RaspiCamControl.h

This is useful as it allows applications to pass around struct
RASPICAM_CAMERA_PARAMETERS * parameters without the need to include
RaspiCamControl.h and all it's dependencies.

Add name to anonymous structs in RaspiCamControl.h

---

host_applications/linux/apps/raspicam/RaspiVid.c

Comments should reflect the actual situation to prevent confusion. Correct data type prevents compiler from complaining.

RaspiVid: Make information in comments correct and fix data type

---

host_applications/linux/apps/raspicam/RaspiVid.c

Replace three separate functions `open_filename`, `open_imv_filename` and `open_pts_filename` by a single `open_filename`.
This change:
- Allows the user to stream motion vectors and timestamps to socket as well
- Removes repetitive code
Also rename `pts_file` to `pts_filename` to avoid confusion as other variables are called `filename` and `imv_filename`.

RaspiVid: Make open_filename() unified

---

interface/khronos/common/khrn_int_common.h

Make UNUSED(x) explicitly cast (x) to void. This fixes a number
of compiler warnings.
See also #188.

Fix definition of UNUSED(x)

---

interface/vcos/pthreads/vcos_platform.h
interface/vcos/vcos_types.h

This function isn't used anywhere, and causes compiler warnings
due to its use of sbrk() without the relevant #defines.
The "pthreads" version of this doesn't do anything sensible: on
a linux system it should look at something like /proc/vmstat,
but that's not what it does. So additionally remove it to avoid
confusion.
See issue #316.

Remove vcos_get_free_mem()

---

buildme

I found out by accident that buildme doesn't do quite enough escaping of the "tr" command's arguments. It was quite puzzling....

buildme: avoid shell expansion of tr expression

---

containers/net/net_sockets.h

The missing bracket would cause compilation error in cpp.

Add end bracket for cpp extern

---

interface/vchiq_arm/vchiq_test.c

vchiq_test is critical for testing vchiq on the upstream kernel which is currently in staging and will support arm64.   This pull request fixes the minimum number of issues to get vchiq_test to run on arm64.
1. Fixes a few casts to use uintptr_t and intptr_t.
2. Fix a race condition which seems to happen the most on arm64 for some reason.
NOTE: I am not attempting to fix the build scripts at this time.

Fix arm64 issues vchiq_test

---

host_applications/linux/apps/hello_pi/hello_mmal_encode/Makefile
host_applications/linux/apps/hello_pi/hello_mmal_encode/mmal_encode.c
host_applications/linux/apps/hello_pi/rebuild.sh

An example showing how to use the image encoder via MMAL to encode a test image into various formats.

hello_pi: Add hello_mmal_encode example

---

host_applications/linux/apps/raspicam/RaspiStill.c
host_applications/linux/apps/raspicam/RaspiVid.c

Setting the restart interval isn't supported on older firmwares, so aborting is a touch excessive as long as it isn't set.
Segmentation option could try opening a null filename.
Option to segment timestamps file as well as encoded data and motion vectors.

3 minor raspicam updates

---

interface/mmal/util/mmal_il.c

Fixes
util/mmal_il.c:776:35: error:
implicit conversion from enumeration type 'enum OMX_BAYERORDERTYPE' to different enumeration type
'OMX_COLOR_FORMATTYPE' (aka 'enum OMX_COLOR_FORMATTYPE') [-Werror,-Wenum-conversion]
{MMAL_ENCODING_UNKNOWN,        OMX_BayerOrderMax}
Signed-off-by: Khem Raj <raj.khem@gmail.com>

mmal: Add missing struct field definition

---

host_applications/linux/apps/raspicam/RaspiVid.c

The raw video output is useful for image processing applications where both motion vectors from encoder and image data are needed. This pull request adds a new `--raw` option which inserts a video splitter component between camera's video output and encoder's input, which allows us to set callback to capture raw video data into a file.
Another option `--raw-format` is introduced which allows us to choose YUV420, RGB or grayscale format.
Parts of the code (video output format configuration and `camera_buffer_callback()`) come from RaspiYUV.c.
The splitter component is created only if the `--raw` option is specified.

RaspiVid: Add raw (YUV420, RGB or grayscale) video output

---

host_applications/linux/apps/raspicam/RaspiStill.c

Changed `cameara` to `camera` in user visible error message.

Fix typo in raspicam/RaspiStill.c

---

host_applications/linux/apps/raspicam/README.md
host_applications/linux/apps/raspicam/RaspiStill.c

In order to use RaspiStill in my application, I had to enable a new user signal handling (`SIGUSR2`) in order to be able to make a capture and exit immediately (ignoring the timeout). I hope that helps! ;)

Added SIGUSR2 signal to capture and exit immediatelly

---

host_applications/linux/apps/raspicam/RaspiStillYUV.c
host_applications/linux/apps/raspicam/RaspiVidYUV.c

Implemented a fix provided by 6x9, ensures that zero or small
camera callback buffer lengths are handled correctly
Fix for issue 365

Fix for Luma mode double sized files in timelapse

---

host_applications/linux/apps/raspicam/RaspiStill.c

Hi guys,
I recently got merged a pull request #368, I noticed that it only worked if verbose flag is active. I know it was a dummy error and I blame myself for that!! As a result, I provide a fix that allows to use `USR2` signal in both executions (verbose and non-verbose) in that pull request.
Apologise for any inconvenience.
Cheers,
Adrian.

SIGUSR2 should capture and exit even if verbose is false

---

CMakeLists.txt
pkgconfig/mmal.pc.in
pkgconfig/vcsm.pc.in

Presently a number of applications use the hardcoded library path for MMAL. I think we would be best to have a pkg-config file for it just like some of the other libraries provided.

Add pkg-config file for mmal

---

host_applications/linux/apps/raspicam/README.md
host_applications/linux/apps/raspicam/RaspiCamControl.c
host_applications/linux/apps/raspicam/RaspiCamControl.h
host_applications/linux/apps/raspicam/RaspiVid.c

Zooming in, out and reset zoom while capturing video. We capture video using raspivid and send to our server. As we use h264 encoding as it is from Raspberry Pi, send to our server and show as it is in our frontend. No reencoding or video transformations, so using other tools to zoom in and zoom out are not suitable for us.

Zooming in, out and reset zoom while capturing video. 

---

host_applications/linux/apps/raspicam/RaspiStill.c

d35be767 relied on state->width/height being zero before setting
up the defaults, but the state structure is just on the stack
in main() and not initialised.
Initialise the whole structure to 0.
https://www.raspberrypi.org/forums/viewtopic.php?f=43&t=175445

RaspiStill: Fix regression in d35be767 - uninitialised variable

---

host_applications/linux/libs/bcm_host/CMakeLists.txt

This fixes the problem where linker flags coming from top level
makefiles or environment are no longer respected anymore. This
is for example important to pass hardening flags to the build
Signed-off-by: Khem Raj <raj.khem@gmail.com>

bcm_host: Honor previously set value of CMAKE_SHARED_LINKER_FLAGS

---

interface/vmcs_host/vc_vchi_dispmanx.c

I think this is copying data *from* VideoCore memory, not *to" VideoCore memory.

[Trivial] Update comment for vc_dispmanx_resource_read_data

---

host_applications/linux/apps/raspicam/imv_examples/README.md

The example split command reads incorrectly due to \*68\* being interpreted as italics in markdown (i.e. it is the equivalent of \<i\>68\<\/i\> in html).

Escaped the * characters in the imv markdown readme

---

interface/vchiq_arm/vchiq_test.c

For cosmetic reasons it is nice to have some indication of what "vchiq_test -f" is doing.
The logging points were chosen to narrow down a Linux 4.11 failure with cache flushing.
ref: http://lists.infradead.org/pipermail/linux-rpi-kernel/2017-April/006149.html

Make vchiq_test functional test more interesting.

---

host_applications/linux/apps/raspicam/RaspiCamControl.c
host_applications/linux/apps/raspicam/RaspiCamControl.h
host_applications/linux/apps/raspicam/RaspiVid.c

This change enables a user to run "raspivid" with various flicker avoidance modes. It was previously discussed at "https://www.raspberrypi.org/forums/viewtopic.php?f=43&t=159115", where "6by9" mentioned the existence of the MMAL option and "cpunks" (me) wrote the patch.
An aspect from which this patch might need improving, is how command lines are parsed and where "static XREF_T flicker_avoid_map[]" is located. To avoid duplication, I placed it in "RaspiCamControl.h", but since I don't know architectural plans for command line parsing, I might have placed it inconveniently for others.

Add command line option for flicker avoidance

---

interface/mmal/util/mmal_component_wrapper.c

There is a bug in MMAL wrapper code that is because of a short allocation for pools and queues. The bug corrupts stack, so some programs exit with error.
Program to reproduce: https://github.com/Terminus-IMRC/mmal-wrapper-issue-short-allocation
Please merge this to your repo.
Thanks.

mmal_wrapper: Fix a short allocation for pools and queues

---

helpers/dtoverlay/dtoverlay.h

Fixes a buildroot build error:
```
/home/serge/noobs/buildroot/output/build/rpi-userland-bc3c52a51315399a9f31ed24049eb4bc81fd1c60/helpers/dtoverlay/dtoverlay.h:74:54: error: unknown type name ‘va_list’
const char *fmt, va_list args);
^
/home/serge/noobs/buildroot/output/build/rpi-userland-bc3c52a51315399a9f31ed24049eb4bc81fd1c60/helpers/dtoverlay/dtoverlay.h:189:33: error: unknown type name ‘DTOVERLAY_LOGGING_FUNC’
void dtoverlay_set_logging_func(DTOVERLAY_LOGGING_FUNC *func);
^
[ 37%] make[3]: *** [host_applications/linux/apps/dtmerge/CMakeFiles/dtmerge.dir/dtmerge.c.o] Error 1
```

Include stdarg.h in dtoverlay.h

---

host_applications/linux/libs/sm/user-vcsm.c
host_applications/linux/libs/sm/user-vcsm.h

This ioctl call was defined in the kernel header, but not implemented to user-vcsm. This call is really useful for using QPU etc.

user-vcsm: Add an interface to get a VideoCore address of handle

---

makefiles/cmake/vmcs.cmake

Currently vc_vchi_dispmanx.h includes vc_vchi_dispmanx_common.h which is
not distributed on install. This limits access to the ELEMENT_CHANGE_*
defines.
It's not needed in the header itself, it works just fine in the
implementation file.

Relocate vc_vchi_dispmanx_common.h include.

---

host_applications/linux/apps/raspicam/RaspiStill.c

Verbose was being disabled when a capture is sent to stdout, but verbose is sent to stderr, so there is no need to disable it.

Verbose is not disabled when capture is streamed

---

interface/mmal/core/mmal_format.c
interface/mmal/core/mmal_port.c
interface/mmal/vc/mmal_vc_api.c

Valgrind complains that various bits of MMAL structures
are used before initialised. They aren't, but are filled
in by the VPU or kernel so are out of sight of Valgrind.
Using calloc for a couple of structures has minimal overhead
and shuts Valgrind up.

MMAL: Use calloc on some structures to make Valgrind happy

---

pkgconfig/vcsm.pc.in

`libvcsm.so` is linked with vcos in https://github.com/raspberrypi/userland/blob/master/host_applications/linux/libs/sm/CMakeLists.txt#L15 , so changed to specify it in pkgconfig file.

pkgconfig: vcsm: Add -lvcos to Libs

---

host_applications/linux/apps/raspicam/RaspiVid.c

The error handling forgot to set an error status, so main continued
on and then seg faulted due to no encoder component.
Fixes #464.

RaspiVid: Return an error if the overall encode exceeds level 4.2

---

interface/khronos/glxx/glxx_client.c

glMapBufferOES fails if the usage hint passed to glBufferData was
GL_STREAM_DRAW because glBufferData does not initialise the cached copy
of the buffer size.
The usage hint doesn't make any functional difference with these
functions and GL_STREAM_DRAW was added in GLES 2.0 so this looks like
an old check which was never updated.
Fixes #246

glxx_client: Fix glMapBufferOES with GL_STREAM_DRAW

---

interface/khronos/glxx/glxx_client.c

glGetBufferParameteriv updates the client side cached copy of the
buffer_size. However, when it updated the cache it by calling
glxx_buffer_info_set it trashed the mapped_pointer and mapped_size
values because they are in the same structure as the cached_size but
this was being allocated on the stack.
The trampled mapped_pointer / mapped_size could cause crashes or invalid
buffer data to be uploaded.
Change to read the current cached value and then modify just the
cached_size preserving whatever was in the cache before.
Fixes #323
Signed-off-by: Tim Gover <tim.gover@raspberrypi.org>

glxx_client: Fix glGetBufferParameteriv GL_BUFFER_SIZE

---

host_applications/linux/apps/raspicam/RaspiStill.c
host_applications/linux/apps/raspicam/RaspiStillYUV.c

When in timelapse mode, the delay before the first shot
was the timelapse value. However, if a low value is set
this does not give enough time for the AE etc to settle.
In addition, the first image was only taken after the
first delay, rather than immediately which is what would
be expected. So a 5minute timelapse delay meant the 1st
image was only taken after 5 minutes.
The patch sets the delay for the first image capture to
be a constant value, 1000ms. So always time for the AE etc
to settle.
Fixes: #429, #473

Fixed up initial timelapse delay

---

host_applications/linux/apps/raspicam/RaspiStill.c
host_applications/linux/apps/raspicam/RaspiVidYUV.c

Support for TGA and PPM encoders to Raspistill
Bug fix to RaspiVidYuv to shut down the correct output port before closing file handles.

Raspicam tweaks

---

host_applications/linux/apps/raspicam/RaspiVid.c
host_applications/linux/apps/raspicam/RaspiVidYUV.c

Option to specify timestamp in the segment filename
In segmented mode, this allows you to specify that the file
name for each segment uses a timestamp, not a segment number.
Activated using %s instead of %d in the filename.

Segment timestamp

---

host_applications/linux/apps/raspicam/RaspiStillYUV.c
host_applications/linux/apps/raspicam/RaspiVidYUV.c

RaspiYuv didn't support -md to set the sensor mode.
Raspividyuv would stall if you didn't set an output file or it failed to open as the output port had already been enabled so was waiting for buffers.

Two more Raspicam fixes

---

interface/mmal/util/mmal_connection.c
interface/mmal/util/mmal_connection.h

There's a slightly quirky use case with deinterlacing.
Interlaced YUV420 is line interleaved, so chroma line 1
is that for luma lines 1&3, and chroma line 2 is for luma lines 2&4.
If you pass such a frame into a standard component (eg the ISP), it
messes up the chroma by assuming chroma line 1 is for luma lines 1&2.
If you pass it into the ISP as double width by half height then the
chroma subsampling behaves correctly. Normally that precludes using
a mmal_connection as that will copy the port format from output
to input. Setting this new flag skips that stage and makes it the
client's responsibilty to set both port formats appropriately.

mmal: Add KEEP_PORT_FORMATS flag to mmal connection

---

host_applications/linux/apps/raspicam/CMakeLists.txt
host_applications/linux/apps/raspicam/Makefile
host_applications/linux/apps/raspicam/RaspiStill.c
host_applications/linux/apps/raspicam/gps.h
host_applications/linux/apps/raspicam/libgps_loader.c
host_applications/linux/apps/raspicam/libgps_loader.h

Applies GPS information from gpsd as EXIF tags.
Enable via "-gps" command line argument and requires libgps.so.22 when
enabled.
Only these GPS info are added as EXIF tags: GPSDateStamp, GPSTimeStamp,
GPSMeasureMode, GPSSatellites, GPSLatitude, GPSLatitudeRef,
GPSLongitude, GPSLongitudeRef, GPSAltitude, GPSAltitudeRef, GPSSpeed,
GPSSpeedRef, GPSTrack, GPSTrackRef.

RaspiStill: Apply gpsd info as EXIF tags

---

host_applications/android/apps/vidtex/CMakeLists.txt
host_applications/linux/apps/hello_pi/hello_mmal_encode/Makefile
host_applications/linux/apps/raspicam/CMakeLists.txt

Some versions of GCC have --as-needed turned on by default.
The binding of libmmal_vc_client is such that the constructor
registers the supported components with the MMAL core, and nothing
calls into it directly. The linker can't tell this, decides
it is unused, and promptly drops it as a dependency - cue no
VideoCore components.
Adding --no-as-needed means that the linker leaves it alone.
It's not nice, but there doesn't appear to be a better solution.
See #178.

host_apps: Add --no-as-needed to stop libmmal_vc_client being dropped

---

host_applications/linux/apps/raspicam/RaspiVid.c

add use MMAL_PARAMETER_VIDEO_ENCODE_SPS_TIMING for correct setup fps in h.264

add sps timings

---

host_applications/linux/apps/raspicam/RaspiStillYUV.c
interface/mmal/core/mmal_port.c

Two unrelated changes.
RaspiStillYuv supported RGB24 but not BGR24. Add it.
Cherry-picking a firmware source commit to userland. Allows flags buffers to be passed without requiring a buffer to also be allocated as long as alloc_size is set to 0.

MMAL & RaspiStillYuv updates

---

host_applications/linux/apps/raspicam/RaspiVid.c

When inserting the time/date stamp into the filename was added
certain combinations of output filename no longer work. As it
was only searching for "%u" or "%d". Specifying %04d would take
the code down the timestamp route but with invalid parameters.
Make the search slightly more intelligent to allow specifying
the number of digits to insert in the filename.

Raspivid: Fix for bug where %04d no longer works.

---

host_applications/linux/apps/raspicam/RaspiCamControl.c
host_applications/linux/apps/raspicam/RaspiCamControl.h
host_applications/linux/apps/raspicam/RaspiStill.c
host_applications/linux/apps/raspicam/RaspiStillYUV.c
host_applications/linux/apps/raspicam/RaspiVid.c
host_applications/linux/apps/raspicam/RaspiVidYUV.c

All the cam apps were duplicating the same code for outputing camera
settings (e.g. exposure), so have moved it to the CamControl file
so we now only have one set.
Also fixed up a couple of missing bad error returns that were not being
translated correctly from the MMAL error to ints.

Moved all camera 'setting' option code to single source

---

host_applications/linux/apps/raspicam/CMakeLists.txt
host_applications/linux/apps/raspicam/RaspiHelpers.c
host_applications/linux/apps/raspicam/RaspiHelpers.h
host_applications/linux/apps/raspicam/RaspiStill.c
host_applications/linux/apps/raspicam/RaspiStillYUV.c
host_applications/linux/apps/raspicam/RaspiVid.c
host_applications/linux/apps/raspicam/RaspiVidYUV.c

Changed CMakeLists.txt for the camera apps to grab the head commit
hash and pass it to the compiler as a define. Use this to version
the apps rather than the never updated version number.

CamApps : Removed version number and replace with commit id

---

host_applications/linux/apps/hello_pi/hello_triangle2/triangle2.c

Fixed #1077: hello_triangle2, vertex attribute for Mandelbrot program is not linked

Fixed #1077: hello_triangle2, 'vertex' attribute for Mandelbrot

---

host_applications/linux/apps/raspicam/CMakeLists.txt
host_applications/linux/apps/raspicam/RaspiCommonSettings.c
host_applications/linux/apps/raspicam/RaspiGPS.c
host_applications/linux/apps/raspicam/RaspiGPS.h
host_applications/linux/apps/raspicam/RaspiStill.c
host_applications/linux/apps/raspicam/RaspiStillYUV.c
host_applications/linux/apps/raspicam/RaspiVid.c
host_applications/linux/apps/raspicam/RaspiVidYUV.c

This involved:
Moving GPS code to own file so can be used in all apps
Adding option in raspivid to apply GPS data to annotation
Enabled with the -gps flag on command line plus -a 2 to turn on
application annotation.

Add GPS annotation to the raspivid output

---

host_applications/linux/apps/raspicam/RaspiHelpers.c
host_applications/linux/apps/raspicam/RaspiHelpers.h
host_applications/linux/apps/raspicam/RaspiStill.c
host_applications/linux/apps/raspicam/RaspiStillYUV.c
host_applications/linux/apps/raspicam/RaspiVid.c
host_applications/linux/apps/raspicam/RaspiVidYUV.c

The camera apps were using vcos_getmicrosecs64 which
was in turn using gettimeofday. This means timelapse code
goes very wrong when the date/time is changed while the
timelapse is being done.
Moved to a scheme based on clock_gettime(CLOCK_MONOTONIC_RAW)
which is not affected by underlying clock changes.

Move to standard Linux  microsecond count

---

host_applications/linux/apps/raspicam/RaspiVid.c
host_applications/linux/apps/raspicam/RaspiVidYUV.c

This little fix will avoid the following message when raspivid is launched by systemd when a client connect to the listenning socket AND ensure the raspivid process exit when TCP connection is closed by the client.
```
janv. 08 14:19:58 raspberrypi raspivid[4770]: mmal: Failed to write buffer data (4096 from 5016)- aborting
````
`raspivid` fail to exit because abort status isn't taken into account when `-t 0` is given in parameter.
My raspberry Pi3 use the following systemd units:
- /etc/systemd/system/raspivid.socket
```
[Unit]
Description=Raspivid Streaming Socket
[Socket]
ListenStream=3333
Accept=yes
MaxConnections=1
SendBuffer=1M
[Install]
WantedBy=sockets.target
```
- /etc/systemd/system/raspivid@.service
```
[Unit]
Description=Raspivid Streaming Instance
[Service] …
```

Allow aborting on write error to stdout when `-t 0` specified

---

interface/vmcs_host/linux/vcfiled/CMakeLists.txt

Cross compile install fails with vcfiled, as it is attempting to write /etc/init.d.  This should be ${CMAKE_INSTALL_PREFIX}/etc/init.d.

fix vcfiled cross-compile install

---

host_applications/linux/apps/raspicam/RaspiHelpers.c

Was using a 32 bit calculation when should have been 64bit.

Fixed up overflow in microsecond timer

---

host_applications/linux/apps/raspicam/RaspiVid.c

Observed on
https://www.raspberrypi.org/forums/viewtopic.php?f=43&t=189830&start=25#p1432589
The raspivid command line
raspivid --raw-format rgb --raw foo.rgb -o foo.h264
actually saved YUV data to foo.rgb as the --raw option reset
raw-format to YUV mode.
Renumber the enums so that YUV is 0, and use the fact the state
structure is memset to 0 (and therefore YUV) to avoid the
-raw parser needing to change the format at all.

raspivid: Stop --raw option resetting --raw-format to YUV

---

host_applications/vmcs/test_apps/mmalcam/Makefile
host_applications/vmcs/test_apps/mmalplay/Makefile

Supercedes #536 as @tvjon is finding his way with git/github.
Minor update over the original in the output file for mmalcam has been amended to be ```mmalcam``` instead of ```mmalplay```

Makefiles for mmalcam and mmalplay

---

README.md
buildme
makefiles/cmake/toolchains/aarch64-linux-gnu.cmake

Supports native builds on aarch64 machines.
Supports making a 64bit build via either cross compiling, or on
aarch64 machines.
Both options require the addition of --arm64 to the command line,
otherwise 32bit libraries will be built.
Cross compiling requires the aarch64-linux-gnu- compile tools to
be installed (packages gcc-5-aarch64-linux-gnu and g++-aarch64-linux-gnu
on Ubuntu).

buildme: Add option for ARM64 builds via either native or cross compile

---

host_applications/linux/apps/raspicam/RaspiVid.c
host_applications/linux/apps/raspicam/RaspiVidYUV.c
interface/mmal/vc/mmal_vc_client.c

Commit texts fairly self explanatory.
JC has just tripped over the VCHI bulk_rx failure one doing a similar thing to #386.
If we can work out how to map back to a list of pages from one of these allocations, then so much the better.

Minor MMAL fixes.

---

host_applications/linux/apps/raspicam/RaspiVid.c

Fix provided by DaveS.
The addition of a NAL flag appears to have broken timestamps with
large buffers. This simplifies the 'if' around timestamps and takes
the NAL change in to account.
Also fixed up some bad code formatting after the if statement. Yes, I know.

Fix for missing timestamps when data exceed one buffers worth

---

host_applications/linux/apps/raspicam/RaspiVid.c

Under certain circumstances, the Linux file system write behind caching
get so much data to write in one go that is causes frames to be dropped.
The current fflush is not sufficient as that only flushes the C library
caches, not the Linux filesystem caches.
This fix forces data to be written to media as soon as it arrives, using
fdatasync().
Note, currently it's conditional on the --flush  command line parameter.

Add media flushing call on when writing bitstream

---

host_applications/linux/apps/hello_pi/hello_teapot/triangle.c
host_applications/linux/apps/hello_pi/hello_teapot/video.c
host_applications/linux/apps/hello_pi/hello_videocube/triangle.c
host_applications/linux/apps/hello_pi/hello_videocube/video.c

The cleanup step in hello_videocube and hello_teapot is never executed because some bits are missing.
This pull request adds intercepts SIGINT and issue the cleanup when the user pressed CTRL-C.
Also this fixes the egl_render freeze when the OMX_StateLoaded is requested and properly disposes the buffer obtained with OMX_UseEGLImage() call

Fix for missing cleanup step for hello_videocube and hello_teapot

---

host_applications/linux/apps/gencmd/gencmd.c
interface/vmcs_host/vc_gencmd_defs.h

The current maximum response size from the firmware is 4096. Increase
the client's buffer to match this.
Additionally, ensure that the buffer is null terminated, otherwise,
strlen could fail.

vcgencmd: Increase buffer size and ensure strings are null terminated

---

host_applications/linux/apps/raspicam/RaspiPreview.c
host_applications/linux/apps/raspicam/RaspiPreview.h

Allows options like -dn 7 to push the preview onto HDMI1.

raspicam: Add -dn option to set the display number

---

host_applications/linux/libs/debug_sym/debug_sym.c

Any kernel not using bcm2708_fb as the FB driver is likely to
fail the FBIODMACOPY ioctl that vcdbg tries to use to access
the hidden 16MB of RAM behind the peripheral space.
Remove the error message as it drops back to using /dev/mem
instead anyway.
Cherry-pick of 21a576f9f74df33f233b18717d225867c912e818 from the firmware tree as that appears not to have happened automagically.

debug_sym: Remove annoying message should fb copy fail

---

host_applications/linux/apps/raspicam/gps.h
host_applications/linux/apps/raspicam/libgps_loader.h

Buster now has gpsd version 23, (up from 22)
This PR updates the camera code to reflect the change.

Update the GPS version to 23

---

host_applications/linux/libs/sm/user-vcsm.c

vcsm_clean_invalid2 created and filled a struct for the older
kernel driver, and this caused problems when used against the
new driver.
Use the correct struct.

uservcsm: Fix incorrect struct type

---

host_applications/linux/libs/sm/user-vcsm.c

VMCS_SM_IOCTL_HOST_WALK_PID_ALLOC and VMCS_SM_IOCTL_HOST_WALK_PID_MAP had been swapped, causing vcsm_status to yield unexpected results.

Fix confusing typo swapping _MAP and _ALLOC

---

interface/vmcs_host/CMakeLists.txt

vcilcs requries libbrcmEGL, libbrcmGLESv2 and libkhrn_client which have
only 32 bit versions currently, so disable it when building aarch64
Signed-off-by: Dagg Stompler <daggs@gmx.com>

vmcs_host/vcilcs: build only on 32 bit

---

host_applications/linux/libs/debug_sym/debug_sym.c
host_applications/linux/libs/debug_sym/debug_sym.h

This allows the use of /dev/mem instead of /dev/vc-mem (ie it
should work on mainline kernel builds.
vcdbg needs the offset and size of memory to work.
The firmware should have inserted these into the kernel
command line as vc_mem.mem_base and vc_mem.mem_size, so libdebugsym
tries to extract those values from /proc/cmdline, or you can
provide them on the command line via -l and -s
(/dev/mem couldn't be used previously as libdebugsym tries to do
lseek(SEEK_END) to get the length, and that isn't supported by
/dev/mem).
This is a cherry-pick of the libdebugsym part of firmware commit e3f9163dc05fa95ceb341497cd65db6aac76b7a0.

vcdbg/debugsym: Add option to specify the file size.

---

interface/vmcs_host/vc_vchi_tvservice.c

This fixes infinity loop at tvservice_wait_for_reply on initialize
with older firmare. [E] No multi display support in firmware!
Checked with `tvservice --list`

tvservice: Fix freeze on old firmware.

---

host_applications/linux/apps/raspicam/RaspiCamControl.c
host_applications/linux/apps/raspicam/RaspiCamControl.h

Add a new option (-fw) in the raspicam applications to display
a Figure of Merit (FoM) value to indicate sharpness in the displayed
region.  A larger value of FoM indicates a sharper image.
This is useful for the HQ camera to help with focussing on a subject.

raspicam: Add option to display focus window with FoM value.

---

host_applications/linux/apps/raspicam/RaspiStill.c
host_applications/linux/apps/raspicam/RaspiStillYUV.c
host_applications/linux/apps/raspicam/RaspiVid.c
host_applications/linux/apps/raspicam/RaspiVidYUV.c

Need to reduce the min fps limit to 0.005 for 200s exposures
available in HQ cam.
Not entirely sure why we have different limits based on exposure, but I have kept that as-is.

raspistill: Adjust framerate limits on long exposures.

---

host_applications/linux/apps/raspicam/RaspiStill.c
host_applications/linux/apps/raspicam/RaspiStillYUV.c
host_applications/linux/apps/raspicam/RaspiVid.c
host_applications/linux/apps/raspicam/RaspiVidYUV.c

Need to reduce the min fps limit to 0.005 for 200s exposures
available in HQ cam.
commit 27db31a8a828c095cb3e35f65d731c7628c587d7 fixed this for the video
port, but we need to do the same for the stills port as well.

raspicam: Adjust framerate limits on long exposures for stills port.

---

interface/mmal/mmal_format.h

MMAL and video_render used not to allow the client to set the column
stride or the chroma offset.
format->es->video.width wasn't actually being used for anything as
mmal_encoding_width_to_stride returns 0 meaning the component has to
compute it.
Add an extra flag for format->flags (MMAL_ES_FORMAT_FLAG_COL_FMTS_WIDTH_IS_COL_STRIDE)
that treats format->es->video.width as the column stride instead of
being ignored.
video_render also used to ignore nSliceHeight (format->es->video.width)
on the column formats.
Adding support in setting that (via vc_image vpitch) means that you can
crop down a larger image with the chroma in a different place.
eg width=(col stride), height=2160, crop.width=1920, crop.height=1080
flags = MMAL_ES_FORMAT_FLAG_COL_FMTS_WIDTH_IS_COL_STRIDE
will display the top left …

MMAL / video_render: Allow column stride to be set on column formats

---

host_applications/linux/apps/raspicam/RaspiStill.c

If exposure and analogue gain are set manually, and we run a stats
pass to setup all other control algorithms, then we can skip the
viewfinder phase and jump straight into captures, saving time over
dropped frames.
Add the relevant logic to allow this.

raspistill: Add option to start in burst mode if AE settings are manual

---

host_applications/linux/apps/tvservice/tvservice.c

This fixes the warning `format ‘%d’ expects argument of type ‘int’, but argument 3 has type ‘size_t’ {aka ‘long unsigned int’}`

Fix a compiler warning

---

interface/vcos/pthreads/vcos_platform.h

Current header generates warnings of the form "warning: cast from
function call of type ‘pthread_t’ {aka ‘long unsigned int’} to
non-matching type ‘VCOS_LLTHREAD_T *’ {aka ‘struct VCOS_LLTHREAD_T *’}
[-Wbad-function-cast]".  Fix that.

Fix cast warning on vcos_llthread_current

---

host_applications/linux/apps/raspicam/RaspiCamControl.c

Queried on https://www.raspberrypi.org/forums/viewtopic.php?f=43&t=292893

RaspiCam: Correct rotation param docs to be 0/90/180/270

---

host_applications/linux/apps/dtmerge/CMakeLists.txt
host_applications/linux/apps/dtmerge/dtmerge.1
host_applications/linux/apps/dtoverlay/CMakeLists.txt
host_applications/linux/apps/dtoverlay/dtoverlay.1
host_applications/linux/apps/dtoverlay/dtparam.1
host_applications/linux/apps/gencmd/CMakeLists.txt
host_applications/linux/apps/gencmd/vcgencmd.1
host_applications/linux/apps/raspicam/CMakeLists.txt
host_applications/linux/apps/raspicam/raspicam.7
host_applications/linux/apps/raspicam/raspistill.1
host_applications/linux/apps/raspicam/raspivid.1
host_applications/linux/apps/raspicam/raspividyuv.1
host_applications/linux/apps/raspicam/raspiyuv.1
host_applications/linux/apps/tvservice/CMakeLists.txt
host_applications/linux/apps/tvservice/tvservice.1
host_applications/linux/apps/vcmailbox/CMakeLists.txt
host_applications/linux/apps/vcmailbox/raspiotp.7
host_applications/linux/apps/vcmailbox/raspirev.7
host_applications/linux/apps/vcmailbox/vcmailbox.1
host_applications/linux/apps/vcmailbox/vcmailbox.7

I've spent a little time going through the excellent raspberry pi documentation site in order to build some man-pages for most of the utilities in the suite. Note that not all utilities are covered here (notably vchiq_test, mmal_vc_diag are missing) but I think it covers the most commonly used utilities.
I've also included some auxilliary man-pages (in section 7) for information relevant to utilities like vcmailbox (covering things like the mailbox info from the wiki-page, and the OTP registers from the documentation site).
I'm happy to make any stylistic / content changes required. If you want to preview how they look currently, you can simply check out the branch and run "man" on the file in question.

Add man-pages for most commands

---

host_applications/linux/libs/sm/user-vcsm.c

Now will properly report errors instead of crashing due to writing to NULL pointer, fixes #690.

vcsm: properly handle too many CMA allocation attempts

---

host_applications/linux/libs/bcm_host/bcm_host.c
host_applications/linux/libs/bcm_host/include/bcm_host.h

bcm_host_is_model_pi4 should be equivalent to a test that the processor
type is BCM2711, so implement it as such (having added BCM2711 as a
recognised processor type and deprecating the name BCM2838).
See: https://github.com/raspberrypi/userland/issues/695
Signed-off-by: Phil Elwell <phil@raspberrypi.com>

bcm_host: Recognise all Pi 4 variants, add BCM2711

---

host_applications/linux/apps/raspicam/RaspiHelpers.c
host_applications/linux/apps/raspicam/RaspiHelpers.h
host_applications/linux/apps/raspicam/RaspiStill.c
host_applications/linux/apps/raspicam/RaspiStillYUV.c
host_applications/linux/apps/raspicam/RaspiVid.c
host_applications/linux/apps/raspicam/RaspiVidYUV.c

If the system is obviously configured for libcamera (for example) by
dint of /dev/video0 being given over to "unicam", complain and abort
immediately. In all other circumstances maintain previous behaviour.
(There seemed to be no obvious place for common code so it is
duplicated. There's not much.)
Signed-off-by: David Plowman <david.plowman@raspberrypi.com>

raspicam: Check system is running legacy camera stack

---

interface/mmal/core/CMakeLists.txt
interface/mmal/core/mmal_component.c
interface/mmal/vc/mmal_vc_api.c
interface/mmal/vc/mmal_vc_api.h

The default linker option with Bullseye appears to now set
as-needed, so as the core doesn't call into mmal_vc_client
it is viewed as unnecesary, missing that mmal_vc_client has
a constructor that registers functions with the core.
Move the registration of the component supplier to the core_init.
The linker is therefore satisfied that mmal_vc_client is used,
and actually links to it.
This allows Picamera to work again.
https://github.com/waveform80/picamera/issues/697
Signed-off-by: Dave Stevenson <dave.stevenson@raspberrypi.com>

mmal: Hack to make mmal core register VideoCore components

---

helpers/dtoverlay/dtoverlay.c
helpers/dtoverlay/dtoverlay.h

1. Literal path string assignments makes it possible to write things like:
`console_uart0 = <&aliases>, "console=", &uart0;`
and let the dtc compiler substitute the path to the node with the  `uart0` label. 
2. Add functions to iterate through subnodes.
3. Adding bcm2712 as a platform allows for Pi 5-specific overlay variants.

Add bcm2712 as a platform and path string assignments
