- host_applications/linux/apps/raspicam/CMakeLists.txt
- host_applications/linux/apps/raspicam/RaspiVidYUV.c
New demo app to produce raw YUV420 video files.
> Added a new camera application, raspividyuv

- host_applications/linux/apps/raspicam/RaspiCamControl.c
- host_applications/linux/apps/raspicam/RaspiCamControl.h
- host_applications/linux/apps/raspicam/RaspiVid.c
Added intra refresh type to raspivid(s)
Added an annotate parameters to allows insertion of various status' to stills or videos.
> Added annotate and intrarefresh settings

- buildme
> Fix typo in buildme shebang

- containers/CMakeLists.txt
See comments in  https://github.com/raspberrypi/userland/commit/3b9ac3ee1da439fefe1a49720ccf0f9b0b4f5121
> Fix build with glibc 2.22

- host_applications/linux/apps/raspicam/RaspiCamControl.c
This small change allows user to include strftime parameters in the annotation.
raspivid -t 5000 --annotate "Camera 1 %Y-%m-%d %X" -o kewl.mp4
> allow annotation string to contain strftime parameters like %Y-%m-%d %X

- host_applications/linux/apps/raspicam/RaspiVid.c
This can be used with mkvmerge:
raspivid -pts timecodes.txt -o video.h264
mkvmerge -o video.mkv --timecodes 0:timecodes.txt video.h264
Original commit by ethanol100. Minor mods by 6by9.
> Raspivid: Add -pts to save timecodes to file

- host_applications/linux/apps/raspicam/RaspiVid.c
Mainly added as an easy way to test for https://www.raspberrypi.org/forums/viewtopic.php?f=43&t=138325
> Raspivid: Add option for MJPEG codec

- host_applications/linux/apps/raspicam/RaspiVid.c
Enable selection of Level 4, 4.1 and 4.2 for H264 codec.
Level will be automatically increased if necessary.
Additional preview buffer will be allocated for higher framerates.
> Add option -lev/--level to raspvid to select H264 Level

- host_applications/linux/apps/raspicam/RaspiStill.c
> RaspiStill: Update annotation before capture

- .gitignore
The build directory (created by ./buildme) should be ignored by git.
> Add build directory to .gitignore

- buildme
No changes other than whitespace.
Thinking about it, I think buildme needs a bit of attention: it should presumably have a way to build for arm64; why only 6 jobs.
> buildme: fix whitespace

- interface/mmal/openmaxil/mmalomx_core.c
- interface/mmal/openmaxil/mmalomx_parameters.c
- interface/mmal/openmaxil/mmalomx_util_params_video.c
Signed-off-by: Khem Raj <raj.khem@gmail.com>
> Fix enum conversion warnings

- host_applications/linux/apps/raspicam/RaspiStill.c
> RaspiStill.c: Fixed a typo

- buildme
- host_applications/linux/apps/raspicam/RaspiStillYUV.c
- host_applications/linux/apps/raspicam/RaspiVid.c
- host_applications/linux/apps/raspicam/RaspiVidYUV.c
A couple of updates that I'd forgotten to create the PR for.
1 - zero copy is the potentially contentious one as it adds the dependency on VCSM, but that isn't an issue on Raspbian where it has been present for at least 2 years.
2 - minor uninitialised variable fix.
3 - raspividyuv is copying code across from raspivid
4 - use nproc jobs in the buildme script.
> raspicam updates

- host_applications/linux/apps/raspicam/RaspiVid.c
Support requests for the TC358743 are getting annoying, so
state that the drivers are unsupported, and are there on an
as-is basis.
> RaspiVid: Print message stating TC358743 drivers are unsupported

- host_applications/linux/apps/raspicam/README.md
Makes viewing much easier to read and  follow along
> raspicam: Improved readme with readme syntax

- host_applications/linux/apps/raspicam/RaspiStill.c
https://github.com/raspberrypi/userland/issues/494
> Delay after first frame, burst-mode #494

- host_applications/linux/apps/raspicam/RaspiVid.c
You could use raspividyuv to do it, but there's no reason to
prevent doing it in raspivid.
Just to make @gsh happy.
> raspivid: Fix so you can record raw without encoding too.

- host_applications/linux/apps/raspicam/RaspiCLI.c
- host_applications/linux/apps/raspicam/RaspiCamControl.c
- host_applications/linux/apps/raspicam/RaspiCamControl.h
- host_applications/linux/apps/raspicam/RaspiPreview.c
- host_applications/linux/apps/raspicam/RaspiStill.c
- host_applications/linux/apps/raspicam/RaspiStillYUV.c
- host_applications/linux/apps/raspicam/RaspiTex.c
- host_applications/linux/apps/raspicam/RaspiTex.h
- host_applications/linux/apps/raspicam/RaspiTexUtil.c
- host_applications/linux/apps/raspicam/RaspiTexUtil.h
- host_applications/linux/apps/raspicam/RaspiVid.c
- host_applications/linux/apps/raspicam/RaspiVidYUV.c
used
astyle -A1 -s3 -w
Not applied to non-RPI sourced code.
No functional changes.
> Reformat of source to userland coding standard

- host_applications/linux/apps/raspicam/CMakeLists.txt
- host_applications/linux/apps/raspicam/RaspiCommonSettings.c
- host_applications/linux/apps/raspicam/RaspiCommonSettings.h
- host_applications/linux/apps/raspicam/RaspiHelpers.c
- host_applications/linux/apps/raspicam/RaspiHelpers.h
- host_applications/linux/apps/raspicam/RaspiStill.c
- host_applications/linux/apps/raspicam/RaspiStillYUV.c
- host_applications/linux/apps/raspicam/RaspiTex.c
- host_applications/linux/apps/raspicam/RaspiVid.c
- host_applications/linux/apps/raspicam/RaspiVidYUV.c
Also involved adding a file for helper functions.
As a indirect result, some features are now available
in the xxxxyuv apps that were originally only in the
non-yuv versions.
> Moved common settings to own file

- host_applications/linux/apps/raspicam/RaspiVid.c
- host_applications/linux/apps/raspicam/RaspiVidYUV.c
Should now mean videos actually save....
Not sure how it happened, possible merge/cherry pick problems when I was shuffling branches.
> Fixes up a merge mistake made when moving filenames to common code

- host_applications/linux/apps/raspicam/RaspiStillYUV.c
- host_applications/linux/apps/raspicam/RaspiVidYUV.c
This brings them in to line with the non-YUV variants.
> Added annotate options to raspiyuv and raspividyuv

- host_applications/linux/apps/gencmd/gencmd.c
Pull in changes from orphaned PR #528: namely add basic usage, detect and report errors to STDERR, add link to forthcoming documentation on the website.
> Improve vcgencmd

- host_applications/linux/libs/sm/user-vcsm.c
It does have potential nasty failure mechanisms should you be
using 64 bit kernels etc, but should work for all current cases.
> vcsm: Add support for vcsm_vc_addr_from_hdl to vcsm-cma path

- host_applications/linux/libs/bcm_host/bcm_host.c
- host_applications/linux/libs/bcm_host/include/bcm_host.h
- host_applications/linux/libs/sm/user-vcsm.c
Cherry-picking @popcornmix 's patch from the firmware branch, and adding one for vcsm-cma cache flushing.
> bcm_host and vcsm patches

- host_applications/linux/libs/sm/user-vcsm.c
If export is not requested, then /dev/vcsm was the only device tried.
On aarch64 we are not including /dev/vcsm as it has too many
32 bit assumptions, therefore the sensible thing is to try
/dev/vcsm-cma, even if export hasn't been explicitly requested.
> vcsm: If /dev/vcsm fails, then try /dev/vcsm-cma not already tried.

- host_applications/linux/apps/raspicam/RaspiStillYUV.c
- host_applications/linux/apps/raspicam/RaspiVidYUV.c
These two apps had missed the relevant calls to configure 3D
capture.
https://github.com/raspberrypi/userland/issues/579
> Raspicam: Add 3D controls to RaspistillYUV and RaspiVidYUV

- host_applications/linux/apps/hello_pi/hello_fft/hello_fft.c
For batch size >= N/2 the test patterns were wrong and created out of bound memory access.
> Fixed hello_fft test cases with larger batch size

- host_applications/linux/libs/bcm_host/include/bcm_host.h
...with info from https://www.raspberrypi.org/documentation/hardware/raspberrypi/revision-codes/README.md
> Update board revision codes

- host_applications/linux/apps/dtoverlay/dtparam.1
> Fix spelling mistake in man file
